{{ if .Values.frontend.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ingress
  annotations:
    metadata.annotations.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: guestbook.pre.com
      http:
        paths:
          - path: /
            backend:
              serviceName: guestbook
              servicePort: 80